Movie/app/models.py
#coding:utf8

from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from datetime import datetime
import pymysql

app = Flask(__name__)
app.config["SQLALCHEMY_DATABASE_URI"] = "mysql+pymysql://root:0270@127.0.0.1:3306/movie?charset=utf8"
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = True

db = SQLAlchemy(app)

#会员
class User(db.Model):
	"""会员数据结构"""
	__tablename__ = "user"
	id = db.Column(db.Integer, primary_key = True)
	name = db.Column(db.String(100), unique = True)
	pwd = db.Column(db.String(100), unique = True)
	email = db.Column(db.String(100), unique = True)
	phone = db.Column(db.String(11), unique = True)
	info = db.Column(db.Text)
	face = db.Column(db.String(255), unique = True)
	addtime = db.Column(db.DateTime, index = True, default = datetime.utcnow)
	uuid = db.Column(db.String(255), unique = True)
	userlogs = db.relationship("UserLog", backref = "user")
	comments = db.relationship("Comment", backref = "user")
	moviecols = db.relationship("Moviecol", backref = "user")
	admins = db.relationship("Admin", backref = "user")

	def __repr__(self):
		return "<User %r>" % self.name

#会员登陆信息
class UserLog(db.Model):
	__tablename__ = "userlog"
	id = db.Column(db.Integer, primary_key = True)
	user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
	ip = db.Column(db.String(100))
	addtime = db.Column(db.DateTime, index = True, default = datetime.utcnow)

	def __repr__(self):
		return "<Userlog %r>" % self.id

#标签
class Tag(db.Model):
	__tablename__ = "tag"
	id = db.Column(db.Integer, primary_key = True)
	name = db.Column(db.String(100), unique = True)
	addtime = db.Column(db.DateTime, index = True, default = datetime.utcnow)
	movies = db.relationship("Movie", backref = "tag")

	def __repr__(self):
		return "<Tag %r>" % self.name

#电影
class Movie(db.Model):
	__tablename__ = "movie"
	id = db.Column(db.Integer, primary_key = True)
	title = db.Column(db.String(255), unique = True)
	url = db.Column(db.String(255), unique = True)
	info = db.Column(db.Text)
	logo = db.Column(db.String(255), unique = True)
	star = db.Column(db.SmallInteger)
	playnum = db.Column(db.BigInteger)
	commentnum = db.Column(db.BigInteger)
	tag_id = db.Column(db.Integer, db.ForeignKey('tag.id'))
	area = db.Column(db.String(255))
	release_time = db.Column(db.Date)
	length = db.Column(db.String(100))
	addtime = db.Column(db.DateTime, index = True, default = datetime.utcnow)
	comments = db.relationship("Comment", backref = "movie")
	moviecols = db.relationship("Moviecol", backref = "movie")

	def __repr__(self):
		return "<Movie %r>" % self.title

#预告
class Preview(db.Model):
	"""电影预报"""
	__tablename__ = "preview"
	id = db.Column(db.Integer, primary_key = True)
	title = db.Column(db.String(255), unique = True)
	logo = db.Column(db.String(255), unique = True)
	addtime = db.Column(db.DateTime, index = True, default = datetime.utcnow)

	def __repr__(self):
		return "<Preview %r>" % self.title

#评论
class Comment(db.Model):
	"""电影评论"""
	__tablename__ = "comment"
	id = db.Column(db.Integer, primary_key = True)
	content = db.Column(db.Text)
	movie_id = db.Column(db.Integer, db.ForeignKey('movie.id'))
	user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
	addtime = db.Column(db.DateTime, index = True, default = datetime.utcnow)

	def __repr__(self):
		return "<Comment %r>" % self.id

#电影收藏
class Moviecol(db.Model):
	"""电影收藏"""
	__tablename__ = "moviecol"
	id = db.Column(db.Integer, primary_key = True)
	movie_id = db.Column(db.Integer, db.ForeignKey('movie.id'))
	user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
	addtime = db.Column(db.DateTime, index = True, default = datetime.utcnow)

	def __repr__(self):
		return "<Moviecol %r>" % self.id

#权限
class Auth(db.Model):
	"""权限"""
	__tablename__ = "auth"
	id = db.Column(db.Integer, primary_key = True)
	name = db.Column(db.String(100), unique = True)
	url = db.Column(db.String(255), unique = True)
	addtime = db.Column(db.DateTime, index = True, default = datetime.utcnow)

	def __repr__(self):
		return "<Auth %r>" % self.name

#角色
class Role(db.Model):
	"""角色"""
	__tablename__ = "role"
	id = db.Column(db.Integer, primary_key = True)
	name = db.Column(db.String(100), unique = True)
	auths = db.Column(db.String(600))
	addtime = db.Column(db.DateTime, index = True, default = datetime.utcnow)

	def __repr__(self):
		return "<Role %r>" % self.name

#管理员
class Admin(db.Model):
	__tablename__ = "admin"
	id = db.Column(db.Integer, primary_key = True)
	name = db.Column(db.String(100), unique = True)
	pwd = db.Column(db.String(100), unique = True)
	is_super = db.Column(db.SmallInteger)
	role_id = db.Column(db.Integer, db.ForeignKey('role.id')) 
	addtime = db.Column(db.DateTime, index = True, default = datetime.utcnow)
	adminlogs = db.relationship("AdminLog", backref = "admin")
	oplogs = db.relationship("Oplog", backref = "admin")

	def __repr__(self):
		return "<Admin %r>" % self.name

#管理员日志
class AdminLog(db.Model):
	__tablename__ = "adminlog"
	id = db.Column(db.Integer, primary_key = True)
	admin_id = db.Column(db.Integer, db.ForeignKey('admin.id'))
	ip = db.Column(db.String(100))
	addtime = db.Column(db.DateTime, index = True, default = datetime.utcnow)

	def __repr__(self):
		return "<Adminlog %r>" % self.id

#操作日志
class Oplog(db.Model):
	__tablename__ = "oplog"
	id = db.Column(db.Integer, primary_key = True)
	admin_id = db.Column(db.Integer, db.ForeignKey('admin.id'))
	ip = db.Column(db.String(100))
	reason = db.Column(db.String(600))
	addtime = db.Column(db.DateTime, index = True, default = datetime.utcnow)

	def __repr__(self):
		return "<Oplog %r>" % self.id

if __name__ == "__main__":
	db.create_all()

Movie/app/__init__.py
#coding:utf8

from flask import Flask, render_template

app = Flask(__name__)
app.debug = True

from app.home import home as home_blueprint
from app.admin import admin as admin_blueprint

app.register_blueprint(home_blueprint)
app.register_blueprint(admin_blueprint, url_prefix="/admin")

@app.errorhandler(404)
def page_not_found(error):
	return render_template("home/404.html"), 404

Movie/app/admin/__init__.py
#coding:utf8

from flask import Blueprint
admin = Blueprint("admin", __name__)

import app.admin.views

Movie/app/admin/views.py
#coding:utf8

from . import admin
from flask import render_template, redirect, url_for

@admin.route("/")
def index():
	return "<h1 style='color:red'>This is admind</h1>"

@admin.route("/login/")
def login():
	return render_template('admin/login.html')

@admin.route("/logout/")
def logout():
	return redirect(url_for("admin.login"))

Movie/app/home/__init__.py
#coding:utf8

from flask import Blueprint
home = Blueprint("home", __name__)

import app.home.views

Movie/app/home/views.py
#coding:utf8

from . import home
from flask import render_template, redirect, url_for

@home.route("/login/")
def login():
	return render_template("home/login.html")

@home.route("/logout/")
def logout():
	return redirect(url_for("home.login"))

@home.route("/register/")
def register():
	return render_template("home/register.html")

@home.route("/user/")
def user():
	return render_template("home/user.html")

@home.route("/pwd/")
def pwd():
	return render_template("home/pwd.html")

@home.route("/comments/")
def comments():
	return render_template("home/comments.html")

@home.route("/loginlog/")
def loginlog():
	return render_template("home/loginlog.html")

@home.route("/moviecol/")
def moviecol():
	return render_template("home/moviecol.html")

@home.route("/")
def index():
	return render_template("home/index.html")

@home.route("/animation/")
def animation():
	return render_template("home/animation.html")

@home.route("/search/")
def search():
	return render_template("home/search.html")

@home.route("/play/")
def play():
	return render_template("home/play.html")

Movie/app/templates/home/home.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>微电影</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename = 'base/images/logo.png') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'base/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename = '/base/css/bootstrap-movie.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'base/css/animate.css') }}">
    <style>
        .navbar-brand>img {
            display: inline;
        }
        .media{
            padding:3px;
            border:1px solid #ccc
        }

    </style>
    {% block css %}{% endblock %}
</head>

<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{{ url_for('home.index') }}" class="navbar-brand" style="width:250px;">
                <img src="{{ url_for('static', filename = 'base/images/logo.png') }}" style="height:30px;">&nbsp;微电影
            </a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" role="search" style="margin-top:18px;">
                <div class="form-group input-group">
                    <input type="text" class="form-control" placeholder="请输入电影名！">
                    <span class="input-group-btn">
                        <a class="btn btn-default" href="{{ url_for('home.search') }}"><span class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>
                    </span>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="curlink" href="{{ url_for('home.index') }}"><span class="glyphicon glyphicon-film"></span>&nbsp;电影</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.login')}}"><span class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.register')}}"><span class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.logout')}}"><span class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.user') }}"><span class="glyphicon glyphicon-user"></span>&nbsp;会员</a>
                </li>
            </ul>
        </div>
        <!--导航-->

    </div>
</nav>
<!--导航-->
<!--内容-->
<div class="container" style="margin-top:76px">
    {% block content %}{% endblock %}
</div>
<!--内容-->
<!--底部-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    ©&nbsp;2017&nbsp;flaskmovie.imooc.com&nbsp;京ICP备 13046642号-2
                </p>
            </div>
        </div>
    </div>
</footer>
<!--底部-->
<script src="{{ url_for('static', filename = 'base/js/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename = 'base/js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static', filename = 'base/js/jquery.singlePageNav.min.js') }}"></script>
<script src="{{ url_for('static', filename = 'base/js/wow.min.js') }}"></script>
<script src="{{ url_for('static', filename = 'lazyload/jquery.lazyload.min.js') }}"></script>
<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
<script>
    $(function() {
        new WOW().init();
    })

</script>
<script>
    $(document).ready(function() {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });
    });

</script>
{% block js %}{% endblock %}
</body>
</html>

Movie/app/templates/home/index.html
{% extends "home/layout.html" %}
{% block content %}
<!--热门电影-->
<section id="hotmovie" style="margin-top:76px">
    <div class="container">
        <div class="row wow fadeInRight" data-wow-delay="0.6s">
            <div class="row">
                <iframe class="wow fadeIn" width="100%" height="375px" frameborder=0 scrolling=no src="{{ url_for('home.animation') }}"></iframe>
            </div>
        </div>
    </div>
</section>
<!--热门电影-->
<!--电影列表-->
<section id="movielist">
    <div class="container">
        <div class="row wow fadeIn" data-wow-delay="0.6s">
            <div class="col-md-12 table-responsive">
                <table class="table text-left table-bordered" id="movietags">
                    <tr>
                        <td style="width:10%;">电影标签</td>
                        <td style="width:90%;">
                            <a class="label label-info"><span class="glyphicon glyphicon-tag"></span>&nbsp;标签一</a>
                            &nbsp;
                            <a class="label label-info"><span class="glyphicon glyphicon-tag"></span>&nbsp;标签一</a>
                            &nbsp;
                            <a class="label label-info"><span class="glyphicon glyphicon-tag"></span>&nbsp;标签一</a>
                            &nbsp;
                            <a class="label label-info"><span class="glyphicon glyphicon-tag"></span>&nbsp;标签一</a>
                            &nbsp;
                            <a class="label label-info"><span class="glyphicon glyphicon-tag"></span>&nbsp;标签一</a>
                    </tr>
                    <tr>
                        <td>电影星级</td>
                        <td>
                            <a class="label label-warning"><span class="glyphicon glyphicon-star"></span>&nbsp;一星</a>
                            &nbsp;
                            <a class="label label-warning"><span class="glyphicon glyphicon-star"></span>&nbsp;二星</a>
                            &nbsp;
                            <a class="label label-warning"><span class="glyphicon glyphicon-star"></span>&nbsp;三星</a>
                            &nbsp;
                            <a class="label label-warning"><span class="glyphicon glyphicon-star"></span>&nbsp;四星</a>
                            &nbsp;
                            <a class="label label-warning"><span class="glyphicon glyphicon-star"></span>&nbsp;五星</a>
                        </td>
                    </tr>
                    <tr>
                        <td>上映时间</td>
                        <td>
                            <a class="label label-default"><span class="glyphicon glyphicon-time"></span>&nbsp;最近</span></a>
                            &nbsp;
                            <a class="label label-default"><span class="glyphicon glyphicon-time"></span>&nbsp;2017</span></a>
                            &nbsp;
                            <a class="label label-default"><span class="glyphicon glyphicon-time"></span>&nbsp;2016</span></a>
                            &nbsp;
                            <a class="label label-default"><span class="glyphicon glyphicon-time"></span>&nbsp;2015</span></a>
                            &nbsp;
                            <a class="label label-default"><span class="glyphicon glyphicon-time"></span>&nbsp;更早</span></a>
                        </td>
                    </tr>
                    <tr>
                        <td>播放数量</td>
                        <td>
                            <a class="label label-success"><span class="glyphicon glyphicon-arrow-down"></span>&nbsp;从高到底</span></a>
                            &nbsp;
                            <a class="label label-danger"><span class="glyphicon glyphicon-arrow-up"></span>&nbsp;从低到高</span></a>
                        </td>
                    </tr>
                    <tr>
                        <td>评论数量</td>
                        <td>
                            <a class="label label-success"><span class="glyphicon glyphicon-arrow-down"></span>&nbsp;从高到底</span></a>
                            &nbsp;
                            <a class="label label-danger"><span class="glyphicon glyphicon-arrow-up"></span>&nbsp;从低到高</span></a>
                        </td>
                    </tr>
                </table>
            </div>
            {% for v in range(1,13) %}
            <div class="col-md-3">
                <div class="movielist text-center">
                    <!--<img data-original="holder.js/262x166"
                             class="img-responsive lazy center-block" alt="">-->
                    <img src="holder.js/262x166" class="img-responsive center-block" alt="">
                    <div class="text-left" style="margin-left:auto;margin-right:auto;width:210px;">
                        <span style="color:#999;font-style: italic;">环太平洋</span><br>
                        <div>
                            <span class="glyphicon glyphicon-star" style="color:#FFD119"></span>
                            <span class="glyphicon glyphicon-star" style="color:#FFD119"></span>
                            <span class="glyphicon glyphicon-star" style="color:#FFD119"></span>
                            <span class="glyphicon glyphicon-star-empty" style="color:#FFD119"></span>
                            <span class="glyphicon glyphicon-star-empty" style="color:#FFD119"></span>
                        </div>
                    </div>
                    <a href="{{ url_for('home.play') }}" class="btn btn-primary" target="_blank" role="button"><span class="glyphicon glyphicon-play"></span>&nbsp;播放</a>
                </div>
            </div>
            {% endfor %}
            <div class="col-md-12">
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        <li>
                            <a href="#" aria-label="First">
                                <span aria-hidden="true">首页</span>
                            </a>
                        </li>
                        <li>
                            <a href="#" aria-label="Previous">
                                <span aria-hidden="true">上一页</span>
                            </a>
                        </li>
                        <li><a href="#">1&nbsp;/&nbsp;10</a></li>
                        <li>
                            <a href="#" aria-label="Next">
                                <span aria-hidden="true">下一页</span>
                            </a>
                        </li>
                        <li>
                            <a href="#" aria-label="Last">
                                <span aria-hidden="true">尾页</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</section>
<!--电影列表-->
{% endblock %}

Movie/app/templates/home/layout.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>微电影</title>
    <link rel="shortcut icon" href="../static/base/images/logo.png">
    <link rel="stylesheet" href="../static/base/css/bootstrap.min.css">
    <link rel="stylesheet" href="../static/base/css/bootstrap-movie.css">
    <link rel="stylesheet" href="../static/base/css/animate.css">
    <style>
        .navbar-brand>img {
            display: inline;
        }

    </style>
    <style>
        .media{
            padding:3px;
            border:1px solid #ccc
        }

    </style>
</head>

<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{{ url_for('home.index') }}" class="navbar-brand" style="width:250px;">
                <img src="../static/base/images/logo.png" style="height:30px;">&nbsp;微电影
            </a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" role="search" style="margin-top:18px;">
                <div class="form-group input-group">
                    <input type="text" class="form-control" placeholder="请输入电影名！">
                    <span class="input-group-btn">
                        <a class="btn btn-default" href="{{ url_for('home.search') }} "><span class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>
                    </span>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="curlink" href="{{ url_for('home.index') }}"><span class="glyphicon glyphicon-film"></span>&nbsp;电影</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.login') }}"><span class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.register') }}"><span class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.logout') }}"><span class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.user') }}"><span class="glyphicon glyphicon-user"></span>&nbsp;会员</a>
                </li>
            </ul>
        </div>
        <!--导航-->

    </div>
</nav>
<!--导航-->
<!--内容-->
{% block content %}{% endblock %}
<!--内容-->
<!--热门电影-->
<section id="hotmovie" style="margin-top:76px">
    <div class="container">
        <div class="row wow fadeInRight" data-wow-delay="0.6s">
            <div class="row">
                <iframe class="wow fadeIn" width="100%" height="375px" frameborder=0 scrolling=no src="{{ url_for('home.animation') }}"></iframe>
            </div>
        </div>
    </div>
</section>
<!--热门电影-->
<!--电影列表-->
<section id="movielist">
    <div class="container">
        <div class="row wow fadeIn" data-wow-delay="0.6s">
            <div class="col-md-12 table-responsive">
                <table class="table text-left table-bordered" id="movietags">
                    <tr>
                        <td style="width:10%;">电影标签</td>
                        <td style="width:90%;">
                            <a class="label label-info"><span class="glyphicon glyphicon-tag"></span>&nbsp;标签一</a>
                            &nbsp;
                            <a class="label label-info"><span class="glyphicon glyphicon-tag"></span>&nbsp;标签一</a>
                            &nbsp;
                            <a class="label label-info"><span class="glyphicon glyphicon-tag"></span>&nbsp;标签一</a>
                            &nbsp;
                            <a class="label label-info"><span class="glyphicon glyphicon-tag"></span>&nbsp;标签一</a>
                            &nbsp;
                            <a class="label label-info"><span class="glyphicon glyphicon-tag"></span>&nbsp;标签一</a>
                    </tr>
                    <tr>
                        <td>电影星级</td>
                        <td>
                            <a class="label label-warning"><span class="glyphicon glyphicon-star"></span>&nbsp;一星</a>
                            &nbsp;
                            <a class="label label-warning"><span class="glyphicon glyphicon-star"></span>&nbsp;二星</a>
                            &nbsp;
                            <a class="label label-warning"><span class="glyphicon glyphicon-star"></span>&nbsp;三星</a>
                            &nbsp;
                            <a class="label label-warning"><span class="glyphicon glyphicon-star"></span>&nbsp;四星</a>
                            &nbsp;
                            <a class="label label-warning"><span class="glyphicon glyphicon-star"></span>&nbsp;五星</a>
                        </td>
                    </tr>
                    <tr>
                        <td>上映时间</td>
                        <td>
                            <a class="label label-default"><span class="glyphicon glyphicon-time"></span>&nbsp;最近</span></a>
                            &nbsp;
                            <a class="label label-default"><span class="glyphicon glyphicon-time"></span>&nbsp;2017</span></a>
                            &nbsp;
                            <a class="label label-default"><span class="glyphicon glyphicon-time"></span>&nbsp;2016</span></a>
                            &nbsp;
                            <a class="label label-default"><span class="glyphicon glyphicon-time"></span>&nbsp;2015</span></a>
                            &nbsp;
                            <a class="label label-default"><span class="glyphicon glyphicon-time"></span>&nbsp;更早</span></a>
                        </td>
                    </tr>
                    <tr>
                        <td>播放数量</td>
                        <td>
                            <a class="label label-success"><span class="glyphicon glyphicon-arrow-down"></span>&nbsp;从高到底</span></a>
                            &nbsp;
                            <a class="label label-danger"><span class="glyphicon glyphicon-arrow-up"></span>&nbsp;从低到高</span></a>
                        </td>
                    </tr>
                    <tr>
                        <td>评论数量</td>
                        <td>
                            <a class="label label-success"><span class="glyphicon glyphicon-arrow-down"></span>&nbsp;从高到底</span></a>
                            &nbsp;
                            <a class="label label-danger"><span class="glyphicon glyphicon-arrow-up"></span>&nbsp;从低到高</span></a>
                        </td>
                    </tr>
                </table>
            </div>
            {% for v in range(1, 13) %}
            <div class="col-md-3">
                <div class="movielist text-center">
                    <!--<img data-original="holder.js/262x166"
                             class="img-responsive lazy center-block" alt="">-->
                    <img src="holder.js/262x166" class="img-responsive center-block" alt="">
                    <div class="text-left" style="margin-left:auto;margin-right:auto;width:210px;">
                        <span style="color:#999;font-style: italic;">环太平洋</span><br>
                        <div>
                            <span class="glyphicon glyphicon-star" style="color:#FFD119"></span>
                            <span class="glyphicon glyphicon-star" style="color:#FFD119"></span>
                            <span class="glyphicon glyphicon-star" style="color:#FFD119"></span>
                            <span class="glyphicon glyphicon-star-empty" style="color:#FFD119"></span>
                            <span class="glyphicon glyphicon-star-empty" style="color:#FFD119"></span>
                        </div>
                    </div>
                    <a href="{{ url_for('home.play') }}" class="btn btn-primary" target="_blank" role="button"><span class="glyphicon glyphicon-play"></span>&nbsp;播放</a>
                </div>
            </div>
            {% endfor %}
            <div class="col-md-12">
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        <li>
                            <a href="#" aria-label="First">
                                <span aria-hidden="true">首页</span>
                            </a>
                        </li>
                        <li>
                            <a href="#" aria-label="Previous">
                                <span aria-hidden="true">上一页</span>
                            </a>
                        </li>
                        <li><a href="#">1&nbsp;/&nbsp;10</a></li>
                        <li>
                            <a href="#" aria-label="Next">
                                <span aria-hidden="true">下一页</span>
                            </a>
                        </li>
                        <li>
                            <a href="#" aria-label="Last">
                                <span aria-hidden="true">尾页</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</section>
<!--电影列表-->
<!--底部-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    ©&nbsp;2017&nbsp;flaskmovie.imooc.com&nbsp;京ICP备 13046642号-2
                </p>
            </div>
        </div>
    </div>
</footer>
<!--底部-->
<script src="../static/base/js/jquery.min.js"></script>
<script src="../static/base/js/bootstrap.min.js"></script>
<script src="../static/base/js/jquery.singlePageNav.min.js"></script>
<script src="../static/base/js/wow.min.js"></script>
<script src="../static/lazyload/jquery.lazyload.min.js"></script>
<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
<script>
    $(function() {
        new WOW().init();
    })

</script>
<script>
    $(document).ready(function() {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });
    });

</script>
</body>
</html>

Movie/app/templates/home/menu.html
<div class="col-md-3">
    <div class="list-group">
        <a id="m-1" href="{{ url_for('home.user') }}" class="list-group-item">
            <span class="glyphicon glyphicon-user"></span>&nbsp;会员中心
        </a>
         <a id="m-2" href="{{ url_for('home.pwd') }}" class="list-group-item">
            <span class="glyphicon glyphicon-lock"></span>&nbsp;修改密码
        </a>
        <a id="m-3" href="{{ url_for('home.comments') }}" class="list-group-item">
            <span class="glyphicon glyphicon-comment"></span>&nbsp;评论记录
        </a>
        <a id="m-4" href="{{ url_for('home.loginlog') }}" class="list-group-item">
            <span class="glyphicon glyphicon-calendar"></span>&nbsp;登录日志
        </a>
        <a id="m-5" href="{{ url_for('home.moviecol') }}" class="list-group-item">
            <span class="glyphicon glyphicon-heart"></span>&nbsp;收藏电影
        </a>
    </div>
</div>